[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["TeaDove <peter.ibragimov@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.67.0"
pydantic = {extras = ["dotenv"], version = "^1.8.2"}
uvicorn = "^0.14.0"
pandas = "^1.3.1"
sklearn = "^0.0"
python-igraph = "^0.9.6"
loguru = "^0.5.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
